apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool
  name: multitool
  namespace: obf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - image: praqma/network-multitool
        imagePullPolicy: Always
        name: network-multitool

